;;; crit-magit-regression-test.el --- Workflow regressions -*- lexical-binding: t; -*-
(require 'crit-magit-test)

(defconst crit-magit-test--fake-dsh
  (expand-file-name "tests/fake-dsh.py"
                    (file-name-directory (or load-file-name buffer-file-name))))

(defmacro crit-magit-test--with-repo (&rest body)
  (declare (indent 0))
  `(let* ((repo (make-temp-file "crit-magit-workflow-" t))
          (default-directory (file-name-as-directory repo)))
     (unwind-protect
         (progn
           (crit-magit--git-output repo "init" "-q")
           (crit-magit--git-output repo "config" "user.email" "test@example.invalid")
           (crit-magit--git-output repo "config" "user.name" "Test")
           ,@body)
       (dolist (buffer (buffer-list))
         (when (and (buffer-live-p buffer)
                    (with-current-buffer buffer
                      (and (or (derived-mode-p 'magit-mode) buffer-file-name)
                           (string-prefix-p (file-name-as-directory repo) default-directory))))
           (kill-buffer buffer)))
       (delete-directory repo t))))

(defun crit-magit-test--wait (predicate)
  "Wait up to five seconds for PREDICATE."
  (let ((deadline (+ (float-time) 5)))
    (while (and (not (funcall predicate)) (< (float-time) deadline))
      (accept-process-output nil .02))
    (should (funcall predicate))))

(ert-deftest crit-magit-regression-midline-and-no-newline ()
  (crit-magit-test-with-diff-buffer
      "@@ -1 +1 @@\n-old\n\\ No newline at end of file\n+new text\n"
    (forward-line 1)
    (let ((start (point)))
      (forward-line 2)
      (forward-char 4)
      (should (equal (crit-magit--hunk-line-info start 1 1) '(added . 1))))))

(ert-deftest crit-magit-regression-region-direction ()
  (crit-magit-test--with-repo
    (crit-magit-test-with-diff-buffer
        "diff --git a/a b/a\n--- a/a\n+++ b/a\n@@ -1 +1,2 @@\n+first\n+second\n"
      (search-forward "+first")
      (let ((beg (- (point) 3)))
        (search-forward "second")
        (let ((end (point)))
          (crit-magit-test-set-region beg end)
          (let ((forward (crit-magit--extract-diff-target)))
            (crit-magit-test-set-region end beg)
            (should (equal forward (crit-magit--extract-diff-target)))
            (should (= (plist-get forward :start-line) 1))
            (should (= (plist-get forward :end-line) 2))))))))

(ert-deftest crit-magit-regression-mixed-region-rejected ()
  (crit-magit-test-with-diff-buffer "-old\n+new\n"
    (should-error (crit-magit--region-line-range 1 1 1 'removed 1 (point-max))
                  :type 'user-error)))

(ert-deftest crit-magit-regression-git-layers-and-unborn ()
  (crit-magit-test--with-repo
    (with-temp-file "a" (insert "initial\n"))
    (crit-magit--git-output repo "add" "a")
    (should (string-match-p "+initial" (crit-magit--working-tree-diff repo)))
    (crit-magit--git-output repo "commit" "-qm" "initial")
    (with-temp-file "a" (insert "staged\n"))
    (crit-magit--git-output repo "add" "a")
    (with-temp-file "a" (insert "initial\n"))
    (let ((diff (crit-magit--working-tree-diff repo)))
      (should (string-match-p "+staged" diff))
      (should (string-match-p "-staged" diff)))))

(ert-deftest crit-magit-regression-git-failure ()
  (let ((repo (make-temp-file "crit-magit-nogit-" t)))
    (unwind-protect
        (should-error (crit-magit--working-tree-diff repo) :type 'user-error)
      (delete-directory repo t))))

(ert-deftest crit-magit-regression-full-request-process ()
  (crit-magit-test--with-repo
    (let ((crit-magit-dsh-command crit-magit-test--fake-dsh)
          (crit-magit--dsh-process nil)
          (crit-magit-dsh-inline-size-limit 20)
          (crit-magit-dsh-model-history-file (expand-file-name "history.json" repo))
          (crit-magit-dsh-selected-model nil)
          (crit-magit--dsh-model-loaded t)
          (prompt (concat "日本語のコメント\n" (make-string 180000 ?x) "\nFINAL DIFF LINE"))
          (result nil))
      (unwind-protect
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (_prompt choices &rest _) (caar choices)))
                    ((symbol-function 'crit-magit--show-review)
                     (lambda (outcome) (setq result outcome))))
            (crit-magit--request-review prompt repo)
            (crit-magit-test--wait (lambda () result))
            (should (eq (car result) 'success))
            (let ((data (json-parse-string (cdr result) :object-type 'alist)))
              (should (equal (alist-get 'prompt data) prompt))
              (should (equal (file-truename (alist-get 'cwd data)) (file-truename repo)))
              (should (string-match-p "mode: read-only" (alist-get 'patch data)))
              (should (alist-get 'permission_denied data))
              (should-not (file-exists-p (alist-get 'patch_path data))))
            (should-not (crit-magit--dsh-running-p)))
        (when (crit-magit--dsh-running-p) (delete-process crit-magit--dsh-process))))))

(ert-deftest crit-magit-regression-acp-timeout-and-optional-close ()
  (dolist (scenario '("hang" "no-close"))
    (let ((crit-magit-dsh-command crit-magit-test--fake-dsh)
          (crit-magit--dsh-process nil)
          (crit-magit-dsh-discovery-timeout (if (equal scenario "hang") .2 3))
          (process-environment (cons (concat "CRIT_MAGIT_TEST_SCENARIO=" scenario)
                                     process-environment))
          (result nil) (count 0) process)
      (unwind-protect
          (progn
            (setq process (crit-magit--start-acp-model-discovery
                           default-directory
                           (lambda (outcome) (setq result outcome count (1+ count)))))
            (crit-magit-test--wait (lambda () result))
            (should (eq (car result) (if (equal scenario "hang") 'error 'success)))
            (should (= count 1))
            (should-not (process-live-p process))
            (should-not (crit-magit--dsh-running-p)))
        (when (and process (process-live-p process)) (delete-process process))))))

(ert-deftest crit-magit-regression-real-magit-workflow ()
  :tags '(integration)
  (skip-unless (require 'magit nil t))
  (crit-magit-test--with-repo
    (with-temp-file "a.txt" (insert "old\n"))
    (crit-magit--git-output repo "add" "a.txt")
    (crit-magit--git-output repo "commit" "-qm" "initial")
    (with-temp-file "a.txt" (insert "new 日本語\nlast line\n"))
    (let ((crit-magit-session-id "workflow")
          (crit-magit-review-after-comment nil)
          (captured nil))
      (with-current-buffer (magit-diff-setup-buffer nil nil nil nil)
        (goto-char (point-min))
        (search-forward "+new")
        (should (crit-magit--section 'hunk))
        (let ((target (crit-magit--extract-diff-target)))
          (should (equal (plist-get target :path) "a.txt"))
          (should (= (plist-get target :start-line) 1))
          (crit-magit--write-comment target "日本語 comment body"))
        (cl-letf (((symbol-function 'crit-magit--request-review)
                   (lambda (prompt _root) (setq captured prompt))))
          (crit-magit-review)
          (should (string-match-p "+last line" captured))
          (goto-char (oref (crit-magit--section 'file) start))
          (crit-magit-review)
          (should (string-match-p "Location: whole file" captured))
          (narrow-to-region (point) (line-end-position))
          (crit-magit-review-whole)
          (should (string-match-p "日本語 comment body" captured))
          (should (string-match-p "+last line" captured))
          (widen)
          (crit-magit-review-session)
          (should (string-match-p "日本語 comment body" captured))
          (should (string-match-p "+last line" captured))))
      (with-current-buffer (magit-status-setup-buffer repo)
        (goto-char (point-min))
        (search-forward "+new")
        (should (= (plist-get (crit-magit--extract-diff-target) :start-line) 1))))))

(ert-deftest crit-magit-regression-request-failure-cleanup ()
  (dolist (scenario '("review-error" "review-hang" "hang" "selection-quit" "startup-error"))
    (crit-magit-test--with-repo
      (let* ((crit-magit-dsh-command crit-magit-test--fake-dsh)
             (crit-magit--dsh-process nil)
             (crit-magit-dsh-discovery-timeout (if (equal scenario "hang") .15 3))
             (crit-magit-dsh-inline-size-limit 10)
             (process-environment (cons (concat "CRIT_MAGIT_TEST_SCENARIO=" scenario)
                                        process-environment))
             (make-temp (symbol-function 'make-temp-file))
             (start-process (symbol-function 'make-process))
             (created nil) (result nil) (count 0))
        (unwind-protect
            (cl-letf (((symbol-function 'make-temp-file)
                       (lambda (prefix &rest args)
                         (let ((file (apply make-temp prefix args)))
                           (when (member prefix '("crit-magit-read-only-"))
                             (push file created))
                           file)))
                      ((symbol-function 'make-process)
                       (lambda (&rest args)
                         (if (and (equal scenario "startup-error")
                                  (equal (plist-get args :name) "crit-magit-acp"))
                             (signal 'file-error '("fixture startup failure"))
                           (apply start-process args))))
                      ((symbol-function 'crit-magit--dsh-choose-model)
                       (lambda (_options)
                         (if (equal scenario "selection-quit")
                             (signal 'quit nil)
                           '("test-provider" . "test-model"))))
                      ((symbol-function 'crit-magit--show-review)
                       (lambda (outcome) (setq result outcome count (1+ count)))))
              (crit-magit--request-review (make-string 1000 ?x) repo)
              (when (equal scenario "review-hang")
                (crit-magit-test--wait (lambda () (eq crit-magit--dsh-stage 'review)))
                (crit-magit-cancel-review))
              (crit-magit-test--wait
               (lambda () (and created (cl-every (lambda (file) (not (file-exists-p file))) created))))
              (should-not (crit-magit--dsh-running-p))
              (crit-magit-test--wait (lambda () result))
              (should (eq (car result) 'error))
              (should (= count 1)))
          (when (crit-magit--dsh-running-p) (delete-process crit-magit--dsh-process)))))))

(ert-deftest crit-magit-regression-session-writer-lock-and-path ()
  (crit-magit-test--with-repo
    (let* ((crit-magit-session-id "locked")
           (target (list :repository repo :path "a" :side 'file))
           (file (crit-magit--session-file repo "locked"))
           (lock (concat file ".lock")))
      (make-directory (file-name-directory file) t)
      (make-directory lock)
      (should-error (crit-magit--write-comment target "blocked") :type 'user-error)
      (should-not (file-exists-p file))
      (should (file-directory-p lock))
      (delete-directory lock)
      (crit-magit--write-comment target "saved")
      (should-not (file-exists-p lock))
      (let ((crit-magit-session-file-function
             (lambda (_root _id) (expand-file-name "outside.md" repo))))
        (should-error (crit-magit--write-comment target "outside") :type 'user-error)))))

(ert-deftest crit-magit-regression-gitignore-crlf ()
  (crit-magit-test--with-repo
    (let ((coding-system-for-write 'utf-8-dos))
      (with-temp-file ".gitignore" (insert "# preserve\nexisting/\n")))
    (crit-magit--ensure-gitignore repo)
    (crit-magit--ensure-gitignore repo)
    (with-temp-buffer
      (insert-file-contents-literally ".gitignore")
      (should (equal (buffer-string) "# preserve\r\nexisting/\r\n.critmagit/\r\n")))))

(ert-deftest crit-magit-regression-comment-while-busy-is-saved ()
  (crit-magit-test--with-repo
    (let ((crit-magit-session-id "busy")
          (crit-magit-review-after-comment t))
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "save while busy"))
                ((symbol-function 'crit-magit--dsh-running-p) (lambda () t))
                ((symbol-function 'crit-magit--review-session-file)
                 (lambda (&rest _) (ert-fail "Must not dispatch while busy"))))
        (crit-magit--comment-target (list :repository repo :path "a" :side 'file)))
      (should (string-match-p "save while busy"
                              (crit-magit--read-file (crit-magit--session-file repo "busy")))))))

(ert-deftest crit-magit-regression-empty-response-is-error ()
  (should (eq (car (crit-magit--dsh-outcome 0 " \n" "diagnostic")) 'error)))

(ert-deftest crit-magit-regression-deleted-file-fallback ()
  (crit-magit-test-with-diff-buffer
      "diff --git a/old b/old\n--- a/old\n+++ /dev/null\n@@ -1 +0,0 @@\n-removed\n"
    (search-forward "removed")
    (should (equal (crit-magit--file-at-point) "old"))))

(ert-deftest crit-magit-draft-status-initial-view ()
  "Starting at the top of real Magit status captures both layers safely."
  :tags '(integration)
  (skip-unless (require 'magit nil t))
  (crit-magit-test--with-repo
    (with-temp-file "a.txt" (insert "old\n"))
    (crit-magit--git-output repo "add" "a.txt")
    (crit-magit--git-output repo "commit" "-qm" "initial")
    (with-temp-file "a.txt" (insert "staged\n"))
    (crit-magit--git-output repo "add" "a.txt")
    (with-temp-file "a.txt" (insert "unstaged\n"))
    (let ((index (crit-magit--git-output repo "diff" "--cached"))
          draft output)
      (unwind-protect
          (progn
            (with-current-buffer (magit-status-setup-buffer repo)
              (goto-char (point-min))
              (crit-magit)
              (setq draft (current-buffer)))
            (with-current-buffer draft
              (should (derived-mode-p 'crit-magit-draft-mode))
              (should-not buffer-read-only)
              (should-not buffer-file-name)
              (should (string-match-p "+staged" (buffer-string)))
              (should (string-match-p "+unstaged" (buffer-string)))
              (insert "日本語で自由にコメント\n```nested```\n")
              (goto-char (point-max))
              (insert "\n末尾のコメント")
              (narrow-to-region (point-min) (+ (point-min) 5))
              (cl-letf (((symbol-function 'crit-magit--show-review)
                         (lambda (outcome) (setq output (cdr outcome))))
                        ((symbol-function 'crit-magit--request-review)
                         (lambda (&rest _) (ert-fail "Export must not call DSH"))))
                (crit-magit-export))
              (should (string-match-p "日本語で自由にコメント" output))
              (should (string-match-p "末尾のコメント" output))
              (should (string-match-p "> ```nested```" output)))
            (should (equal (crit-magit--read-file (expand-file-name "a.txt" repo)) "unstaged\n"))
            (should (equal index (crit-magit--git-output repo "diff" "--cached")))
            (should-not (file-exists-p (expand-file-name ".critmagit" repo)))
            (should-not (file-exists-p (expand-file-name ".gitignore" repo))))
        (when (buffer-live-p draft)
          (with-current-buffer draft (set-buffer-modified-p nil))
          (kill-buffer draft))))))

(ert-deftest crit-magit-draft-two-actions-and-snapshot ()
  (with-temp-buffer
    (crit-magit-draft-mode)
    (setq crit-magit--draft-root "/tmp/repo" crit-magit--draft-head "abc")
    (crit-magit--draft-initialize "@@ -1 +1 @@\n-old\n+new\n")
    (insert "自由なコメント\n")
    (let (sent exported accepted)
      (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) ?1))
                ((symbol-function 'crit-magit--request-review)
                 (lambda (prompt root callback)
                   (setq sent (cons prompt root) accepted callback))))
        (crit-magit-submit))
      (insert "送信後の編集")
      (funcall accepted)
      (should (buffer-live-p (current-buffer)))
      (should (string-match-p "自由なコメント" (car sent)))
      (should-not (string-match-p "送信後の編集" (car sent)))
      (should (equal (cdr sent) "/tmp/repo"))
      (let ((draft (current-buffer)))
        (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) ?2))
                  ((symbol-function 'crit-magit--show-review)
                   (lambda (outcome) (setq exported outcome))))
          (crit-magit-submit))
        (should-not (buffer-live-p draft)))
      (should (eq (car exported) 'success))
      (should (string-match-p "送信後の編集" (cdr exported))))))

(ert-deftest crit-magit-clipboard-complete-text-and-failure ()
  (let ((kill-ring nil) copied)
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
              ((symbol-function 'gui-set-selection)
               (lambda (selection value)
                 (should (eq selection 'CLIPBOARD)) (setq copied value))))
      (should (crit-magit--copy-review "全文\nline two\n"))
      (should (equal copied (car kill-ring))))
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
              ((symbol-function 'gui-set-selection)
               (lambda (&rest _) (error "Clipboard unavailable"))))
      (should-not (crit-magit--copy-review "fallback"))
      (should (equal (car kill-ring) "fallback")))))

(ert-deftest crit-magit-review-result-copy-notice ()
  (let ((crit-magit-dsh-review-buffer-name " *crit-magit-result-test*") copied)
    (unwind-protect
        (cl-letf (((symbol-function 'crit-magit--copy-review)
                   (lambda (text) (setq copied text) t)))
          (crit-magit--show-review '(success . "# Review\n日本語\n"))
          (with-current-buffer crit-magit-dsh-review-buffer-name
            (should (equal copied (buffer-string)))
            (should (string-match-p "クリップボード" header-line-format))
            (should buffer-read-only)))
      (kill-buffer crit-magit-dsh-review-buffer-name))))

(ert-deftest crit-magit-acp-rejects-incomplete-reviews ()
  (dolist (scenario '("model-mismatch" "empty-answer" "cancelled-answer"))
    (let ((crit-magit-dsh-command crit-magit-test--fake-dsh)
          (crit-magit--dsh-process nil)
          (process-environment (cons (concat "CRIT_MAGIT_TEST_SCENARIO=" scenario)
                                     process-environment)) result)
      (cl-letf (((symbol-function 'crit-magit--dsh-choose-model)
                 (lambda (_) '("test-provider" . "test-model"))))
        (crit-magit--start-acp-model-discovery
         default-directory (lambda (outcome) (setq result outcome)) "review")
        (crit-magit-test--wait (lambda () result))
        (should (eq (car result) 'error))
        (should-not (crit-magit--dsh-running-p))))))

(ert-deftest crit-magit-progress-does-not-open-window ()
  (cl-letf (((symbol-function 'display-buffer)
             (lambda (&rest _) (ert-fail "Progress must stay in echo area"))))
    (crit-magit--progress-open)))

(ert-deftest crit-magit-acp-foreign-updates-and-client-writes ()
  "Foreign session output and client write requests cannot enter a review."
  (let ((state (list :session-id "own" :phase 'prompt :chunks nil :finished nil))
        replies)
    (crit-magit--acp-review-update
     state '((sessionId . "other")
             (update . ((sessionUpdate . "agent_message_chunk")
                        (content . ((type . "text") (text . "foreign")))))))
    (should-not (plist-get state :chunks))
    (cl-letf (((symbol-function 'process-send-string)
               (lambda (_ text) (push (json-parse-string text :object-type 'alist) replies))))
      (dolist (method '("fs/write_text_file" "terminal/create"))
        (crit-magit--acp-review-message
         nil state #'ignore `((id . 91) (method . ,method) (params . nil)))))
    (should (= (length replies) 2))
    (dolist (reply replies)
      (should (= (alist-get 'code (alist-get 'error reply)) -32601)))))

(defconst crit-magit-test--annotated-diff
  (concat "Unstaged changes (index to worktree):\n"
          "diff --git a/init.el b/init.el\n--- a/init.el\n+++ b/init.el\n"
          "@@ -1601,2 +1601,2 @@\n"
          "-  (\"C-c r\" . crit-magit-review)\n"
          "+  (\"C-c r\" . crit-magit)\n"
          " context\n"))

(defmacro crit-magit-test--with-draft (&rest body)
  (declare (indent 0))
  `(with-temp-buffer
     (crit-magit-draft-mode)
     (setq crit-magit--draft-root "/tmp/repo" crit-magit--draft-head "abc")
     (crit-magit--draft-initialize crit-magit-test--annotated-diff)
     ,@body))

(ert-deftest crit-magit-draft-inline-comments-keep-original-diff ()
  "Reproduce the user's global question and comment inserted in a deleted line."
  (crit-magit-test--with-draft
    (insert "これは便利か？\n\n")
    (search-forward "crit-magit-review)")
    (insert " ;;;; この辺余計だったよね")
    (search-forward "crit-magit)")
    (insert " 追加側のコメント")
    (let* ((comments (crit-magit--draft-comments))
           (markdown (crit-magit--draft-markdown))
           (reference (substring markdown (string-match "```diff\n" markdown))))
      (should (= (length comments) 3))
      (should (eq (plist-get (caar comments) :side) 'overall))
      (should (equal (plist-get (car (nth 1 comments)) :path) "init.el"))
      (should (eq (plist-get (car (nth 1 comments)) :side) 'removed))
      (should (= (plist-get (car (nth 1 comments)) :line) 1601))
      (should (eq (plist-get (car (nth 2 comments)) :side) 'added))
      (should (string-match-p "> これは便利か？" markdown))
      (should (string-match-p "> ;;;; この辺余計だったよね" markdown))
      (should-not (string-match-p "この辺余計" reference))
      (should (string-match-p (regexp-quote crit-magit-test--annotated-diff) reference)))))

(ert-deftest crit-magit-draft-source-protection-survives-rejected-edit ()
  (crit-magit-test--with-draft
    (search-forward "crit-magit-review")
    (dotimes (_ 2)
      (should-error (delete-region (- (point) 3) (point)) :type 'text-read-only))
    (insert "コメント")
    (delete-char -2)
    (should (equal (cdar (crit-magit--draft-comments)) "コメ"))
    (should (equal crit-magit--draft-original crit-magit-test--annotated-diff))))

(ert-deftest crit-magit-draft-comment-undo-and-redo ()
  (crit-magit-test--with-draft
    (search-forward "crit-magit-review)")
    (undo-boundary)
    (insert " コメント")
    (undo-boundary)
    (undo-only 1)
    (should-not (crit-magit--draft-comments))
    (undo-redo)
    (should (equal (cdar (crit-magit--draft-comments)) " コメント"))
    (should (eq (plist-get (caar (crit-magit--draft-comments)) :side) 'removed))))

(ert-deftest crit-magit-draft-pasted-source-is-a-comment ()
  (crit-magit-test--with-draft
    (search-forward "-  (")
    (let ((copied (buffer-substring (line-beginning-position) (line-end-position))))
      (end-of-line)
      (insert copied)
      (should (equal (substring-no-properties copied)
                     (cdar (crit-magit--draft-comments)))))))

(ert-deftest crit-magit-draft-closes-only-on-successful-submission ()
  (dolist (choice '(?1 ?2))
    (crit-magit-test--with-draft
      (insert "コメント\n")
      (let ((draft (current-buffer)) accepted)
        (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) choice))
                  ((symbol-function 'crit-magit--request-review)
                   (lambda (_prompt _root callback) (setq accepted callback)))
                  ((symbol-function 'crit-magit--show-review) #'ignore))
          (crit-magit-submit))
        (when (= choice ?1)
          (should (buffer-live-p draft))
          (funcall accepted))
        (should-not (buffer-live-p draft))))))

(ert-deftest crit-magit-draft-cancel-and-errors-retain-comments ()
  (crit-magit-test--with-draft
    (insert "失わないコメント\n")
    (let ((draft (current-buffer)))
      (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) (signal 'quit nil))))
        (should (eq (condition-case nil (crit-magit-submit) (quit 'quit)) 'quit)))
      (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) ?2))
                ((symbol-function 'crit-magit--show-review)
                 (lambda (&rest _) (error "Display failed"))))
        (should-error (crit-magit-submit)))
      (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) ?1))
                ((symbol-function 'crit-magit--request-review)
                 (lambda (&rest _) nil)))
        (crit-magit-submit))
      (should (buffer-live-p draft))
      (should (string-match-p "失わないコメント" (crit-magit--draft-markdown))))))

(ert-deftest crit-magit-draft-acp-submission-lifecycle ()
  "Only sending session/prompt closes a draft; late failures retain its payload."
  (dolist (scenario '("normal" "selection-quit" "review-error"))
    (crit-magit-test--with-repo
      (crit-magit-test--with-draft
        (setq crit-magit--draft-root repo)
        (insert "復元できるコメント\n")
        (let ((draft (current-buffer))
              (crit-magit-dsh-command crit-magit-test--fake-dsh)
              (crit-magit--dsh-process nil)
              (process-environment (cons (concat "CRIT_MAGIT_TEST_SCENARIO=" scenario)
                                         process-environment)) result)
          (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) ?1))
                    ((symbol-function 'crit-magit--dsh-choose-model)
                     (lambda (_)
                       (if (equal scenario "selection-quit") (signal 'quit nil)
                         '("test-provider" . "test-model"))))
                    ((symbol-function 'crit-magit--show-review)
                     (lambda (outcome) (setq result outcome))))
            (crit-magit-submit)
            (should (buffer-live-p draft))
            (crit-magit-test--wait (lambda () result))
            (if (equal scenario "selection-quit")
                (should (buffer-live-p draft))
              (crit-magit-test--wait (lambda () (not (buffer-live-p draft))))))
          (should (eq (car result) (if (equal scenario "normal") 'success 'error)))
          (should (string-match-p "復元できるコメント" (cdr result))))))))

(ert-deftest crit-magit-draft-magit-diff-location ()
  :tags '(integration)
  (skip-unless (require 'magit nil t))
  (crit-magit-test--with-repo
    (with-temp-file "example.txt" (insert "old\n"))
    (crit-magit--git-output repo "add" "example.txt")
    (crit-magit--git-output repo "commit" "-qm" "initial")
    (with-temp-file "example.txt" (insert "new\n"))
    (let (draft)
      (unwind-protect
          (progn
            (with-current-buffer (magit-diff-setup-buffer nil nil nil nil)
              (crit-magit)
              (setq draft (current-buffer)))
            (with-current-buffer draft
              (search-forward "+new")
              (insert " この行へのコメント")
              (let ((anchor (caar (crit-magit--draft-comments))))
                (should (equal (plist-get anchor :path) "example.txt"))
                (should (eq (plist-get anchor :side) 'added))
                (should (= (plist-get anchor :line) 1)))))
        (when (buffer-live-p draft)
          (with-current-buffer draft (set-buffer-modified-p nil))
          (kill-buffer draft))))))

(defconst crit-magit-test--navigation-diff
  (concat "Staged changes (HEAD to index):\n"
          "diff --git a/a b/a\n--- a/a\n+++ b/a\n"
          "@@ -1 +1 @@\n-old a\n+new a\n"
          "@@ -10 +10 @@\n-old again\n+new again\n"
          "diff --git a/b b/b\n--- a/b\n+++ b/b\n"
          "@@ -1 +1 @@\n-old b\n+new b\n"
          "\nUnstaged changes (index to worktree):\n"
          "diff --git a/a b/a\n--- a/a\n+++ b/a\n"
          "@@ -1 +1 @@\n-new a\n+working a\n"))

(defmacro crit-magit-test--with-navigation (&rest body)
  (declare (indent 0))
  `(with-temp-buffer
     (crit-magit-draft-mode)
     (setq crit-magit--draft-root "/tmp/repo" crit-magit--draft-head "abc")
     (crit-magit--draft-initialize crit-magit-test--navigation-diff)
     ,@body))

(defun crit-magit-test--press (key)
  "Invoke the binding for KEY with its actual last input event."
  (let* ((keys (kbd key))
         (last-command-event (aref keys (1- (length keys)))))
    (call-interactively (key-binding keys))))

(ert-deftest crit-magit-navigation-visible-hierarchy ()
  (crit-magit-test--with-navigation
    (should (equal (mapcar #'crit-magit--draft-section-kind crit-magit--draft-sections)
                   '(group file hunk hunk file hunk group file hunk)))
    (crit-magit-test--press "n")
    (should (looking-at "diff --git a/a"))
    (crit-magit-test--press "n")
    (should (looking-at "@@ -1"))
    (search-forward "+new a")
    (crit-magit-test--press "p")
    (should (looking-at "@@ -1"))
    (crit-magit-test--press "p")
    (should (looking-at "diff --git a/a"))
    (crit-magit-test--press "TAB")
    (should (invisible-p (crit-magit--draft-section-start (nth 2 crit-magit--draft-sections))))
    (crit-magit-test--press "n")
    (should (looking-at "diff --git a/b"))
    (crit-magit-test--press "p")
    (should (looking-at "diff --git a/a"))
    (crit-magit-test--press "TAB")
    (crit-magit-test--press "n")
    (should (looking-at "@@ -1"))
    (crit-magit-test--press "TAB")
    (crit-magit-test--press "n")
    (should (looking-at "@@ -10"))))

(ert-deftest crit-magit-navigation-list-fold-preserves-child-fold ()
  (crit-magit-test--with-navigation
    (crit-magit-draft-next)
    (crit-magit-draft-toggle)
    (crit-magit-draft-previous)
    (should (looking-at "Staged changes"))
    (crit-magit-draft-toggle)
    (crit-magit-draft-next)
    (should (looking-at "Unstaged changes"))
    (crit-magit-draft-previous)
    (crit-magit-draft-toggle)
    (crit-magit-draft-next)
    (should (looking-at "diff --git a/a"))
    (crit-magit-draft-next)
    (should (looking-at "diff --git a/b"))))

(ert-deftest crit-magit-navigation-comments-and-folded-export ()
  (crit-magit-test--with-navigation
    (crit-magit-test--press "i")
    (crit-magit-test--press "n")
    (crit-magit-test--press "p")
    (crit-magit-test--press "TAB")
    (crit-magit-test--press "i")
    (should (equal (cdar (crit-magit--draft-comments)) "\nnp\ti"))
    ;; At the boundary after a global comment, explicit navigation must restore n/p.
    (crit-magit-test--press "C-c C-n")
    (should (looking-at "diff --git a/a"))
    (crit-magit-test--press "n")
    (should (looking-at "@@ -1"))
    (search-forward "+new a")
    (crit-magit-test--press "i")
    (insert "行コメント ")
    (crit-magit-test--press "n")
    (crit-magit-test--press "p")
    (let ((markdown (crit-magit--draft-markdown))
          (tick (buffer-chars-modified-tick)))
      (goto-char (crit-magit--draft-section-start (car crit-magit--draft-sections)))
      (crit-magit-draft-toggle)
      (should (= tick (buffer-chars-modified-tick)))
      (should (equal markdown (crit-magit--draft-markdown)))
      (crit-magit-draft-next)
      (should (looking-at "Unstaged changes")))))

(ert-deftest crit-magit-navigation-markers-survive-undo ()
  (crit-magit-test--with-navigation
    (insert "全体コメント\n")
    (undo-boundary)
    (undo-only 1)
    (undo-redo)
    (crit-magit-draft-next)
    (should (looking-at "Staged changes"))
    (crit-magit-draft-next)
    (should (looking-at "diff --git a/a"))
    (crit-magit-draft-toggle)
    (crit-magit-draft-next)
    (should (looking-at "diff --git a/b"))
    (should (equal (cdar (crit-magit--draft-comments)) "全体コメント\n"))))

(ert-deftest crit-magit-navigation-search-reveal-and-cleanup ()
  (crit-magit-test--with-navigation
    (crit-magit-draft-toggle)
    (let* ((section (car crit-magit--draft-sections))
           (overlay (crit-magit--draft-section-overlay section))
           (marker (crit-magit--draft-section-start section)))
      (should (overlay-get overlay 'invisible))
      (funcall (overlay-get overlay 'isearch-open-invisible) overlay)
      (should-not (overlay-get overlay 'invisible))
      (fundamental-mode)
      (should-not (overlay-buffer overlay))
      (should-not (marker-buffer marker)))))

(ert-deftest crit-magit-navigation-keyboard-command-loop ()
  (crit-magit-test--with-navigation
    (save-window-excursion
      (switch-to-buffer (current-buffer))
      (execute-kbd-macro (kbd "n TAB n p <tab> n"))
      (should (looking-at "@@ -1"))
      (execute-kbd-macro (kbd "i n p i"))
      (should (string-match-p "npi" (cdar (crit-magit--draft-comments))))
      (execute-kbd-macro (kbd "C-c <tab>"))
      (should (looking-at "@@ -1"))
      (should (overlay-get
               (crit-magit--draft-section-overlay (crit-magit--draft-section-at-point))
               'invisible)))))

(ert-deftest crit-magit-navigation-real-magit-sections ()
  :tags '(integration)
  (skip-unless (require 'magit nil t))
  (crit-magit-test--with-repo
    (dolist (path '("a.txt" "b.txt")) (with-temp-file path (insert "old\n")))
    (crit-magit--git-output repo "add" ".")
    (crit-magit--git-output repo "commit" "-qm" "initial")
    (dolist (path '("a.txt" "b.txt")) (with-temp-file path (insert "new\n")))
    (let (draft)
      (unwind-protect
          (progn
            (with-current-buffer (magit-diff-setup-buffer nil nil nil nil)
              (crit-magit)
              (setq draft (current-buffer)))
            (with-current-buffer draft
              (let ((files (cl-remove-if-not
                            (lambda (s) (eq (crit-magit--draft-section-kind s) 'file))
                            crit-magit--draft-sections)))
                (should (= (length files) 2))
                (goto-char (crit-magit--draft-section-start (car files)))
                (crit-magit-test--press "TAB")
                (crit-magit-test--press "n")
                (should (= (point) (crit-magit--draft-section-start (cadr files)))))))
        (when (buffer-live-p draft) (kill-buffer draft))))))

(provide 'crit-magit-regression-test)
