;;; live-dsh.el --- Explicit opt-in Magit to real DSH check -*- lexical-binding: t; -*-
;; This script sends synthetic review data to the configured real model.
;; Run only explicitly with CRIT_MAGIT_LIVE_DSH set to the executable path.
;; Magit and dependencies must already be available on load-path.
(unless (getenv "CRIT_MAGIT_LIVE_DSH")
  (error "Set CRIT_MAGIT_LIVE_DSH explicitly to opt in to a real AI request"))
(require 'magit)
(require 'crit-magit)
(require 'cl-lib)
(let* ((root (make-temp-file "crit-magit-live-" t))
       (default-directory (file-name-as-directory root))
       (crit-magit-dsh-command (expand-file-name (getenv "CRIT_MAGIT_LIVE_DSH")))
       (crit-magit-session-id "live-check")
       (crit-magit-review-after-comment nil)
       (crit-magit-dsh-inline-size-limit 16000)
       (result nil) (comment-id nil) (chosen nil)
       (before nil) (source nil)
       (tag (concat "TAIL_" (substring (secure-hash 'sha256 (format "%s" (float-time))) 0 12))))
  (unwind-protect
      (progn
        (crit-magit--git-output root "init" "-q")
        (crit-magit--git-output root "config" "user.email" "fixture@example.invalid")
        (crit-magit--git-output root "config" "user.name" "Fixture")
        (with-temp-file "calc.py" (insert "def divide(a, b):\n    return a / b\n"))
        (crit-magit--git-output root "add" "calc.py")
        (crit-magit--git-output root "commit" "-qm" "fixture")
        (with-temp-file "calc.py"
          (insert "def divide(a, b):\n    return a / (b - 1)\n")
          (dotimes (i 260)
            (insert (format "# fixture padding %03d: unchanged behavior, review transport coverage only.\n" i)))
          (insert (format "# evidence_marker = %s\n" tag)))
        (setq source (crit-magit--read-file "calc.py"))
        (with-current-buffer (magit-diff-setup-buffer nil nil nil nil)
          (goto-char (point-min))
          (search-forward "+    return")
          (setq comment-id
                (plist-get
                 (crit-magit--write-comment
                  (crit-magit--extract-diff-target)
                  "b=1 の場合に何が起きるか確認してください。日本語で簡潔に回答し、このコメントID、diff末尾の evidence_marker の値、問題のある行を明記してください。パディング行の列挙は不要です。ファイルは変更しないでください。")
                 :id))
          (setq before (crit-magit--buffer-diff))
          (cl-letf (((symbol-function 'crit-magit--dsh-choose-model)
                     (lambda (options)
                       (setq chosen (crit-magit--dsh-model-current-selection options))
                       (unless (assoc (crit-magit--dsh-selection-label chosen)
                                      (mapcar (lambda (choice)
                                                (cons (crit-magit--dsh-selection-label (cdr choice)) (cdr choice)))
                                              (crit-magit--dsh-model-options options)))
                         (error "Current model not offered"))
                       chosen))
                    ((symbol-function 'crit-magit--show-review)
                     (lambda (outcome) (setq result outcome))))
            (crit-magit-review-whole)
            (let ((deadline (+ (float-time) 180)))
              (while (and (not result) (< (float-time) deadline))
                (accept-process-output nil .1)))
            (unless result (error "Live review timed out"))))
        (princ (format "MODEL=%S\nCAPTURED_DIFF_BYTES=%d\nOUTCOME=%s\nRESPONSE:\n%s\n"
                       chosen (string-bytes before) (car result) (cdr result)))
        (unless (eq (car result) 'success) (error "DSH live review failed"))
        (unless (string-match-p (regexp-quote tag) (cdr result))
          (error "Response does not contain the captured diff tail marker"))
        (unless (string-match-p (regexp-quote comment-id) (cdr result))
          (error "Response does not contain the captured comment ID"))
        (unless (or (string-match-p "ZeroDivisionError" (cdr result))
                    (string-match-p "ゼロ除算\\|0 除算\\|0除算" (cdr result)))
          (error "Response does not identify the division-by-zero defect"))
        (unless (equal source (crit-magit--read-file (expand-file-name "calc.py" root)))
          (error "Review-only request modified source"))
        (princ "LIVE_REVIEW_VERIFIED=true\n"))
    (when (crit-magit--dsh-running-p) (delete-process crit-magit--dsh-process))
    (dolist (buffer (buffer-list))
      (when (and (buffer-live-p buffer)
                 (with-current-buffer buffer
                   (and (derived-mode-p 'magit-mode)
                        (string-prefix-p (file-name-as-directory root) default-directory))))
        (kill-buffer buffer)))
    (delete-directory root t)))
